### ISSUE TITLE
Add expression check

### ISSUE THREAD

**Issue by titusjaka** [moira-alert/web#18]
Is it possible to add an expression check in target field?

![2016-04-06_19-05-06 2](https://cloud.githubusercontent.com/assets/5277948/14319449/aa294bf0-fc2a-11e5-9fec-9eed4ac2d876.png)

Thank you in advance!

**Comment by gmlexx** [comment]
1) You can not save trigger if expression evaluated with exception.

2) Unfortunately it is not possible to check metrics existence or make any suggestion like grafana does before saving trigger, because moira-cache will accept metrics matched to the trigger's targets only after saving the trigger.

Anyway, the right "devops" way is create triggers automatically to archive the goal.
